"""Initial migration

Revision ID: aaaba51d942f
Revises: 
Create Date: 2024-12-14 19:35:34.051373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaaba51d942f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tick_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tick_data', schema=None) as batch_op:
        batch_op.create_index('idx_market_timestamp', ['market', 'timestamp'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('deriv_api_key', sa.String(length=256), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_suspended', sa.Boolean(), nullable=True),
    sa.Column('suspension_reason', sa.String(length=256), nullable=True),
    sa.Column('suspension_duration', sa.Integer(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('real_account_approved', sa.Boolean(), nullable=True),
    sa.Column('approval_status', sa.String(length=20), nullable=True),
    sa.Column('approval_date', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('is_api_approved', sa.Boolean(), nullable=True),
    sa.Column('api_account_type', sa.String(length=10), nullable=True),
    sa.Column('api_key_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('initial_stake', sa.Float(), nullable=True),
    sa.Column('martingale_multiplier', sa.Float(), nullable=True),
    sa.Column('max_losses', sa.Integer(), nullable=True),
    sa.Column('selected_market', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('strategy_short_ema', sa.Integer(), nullable=True),
    sa.Column('strategy_long_ema', sa.Integer(), nullable=True),
    sa.Column('strategy_bb_period', sa.Integer(), nullable=True),
    sa.Column('strategy_bb_std', sa.Float(), nullable=True),
    sa.Column('strategy_rsi_period', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('stake', sa.Float(), nullable=False),
    sa.Column('trade_type', sa.String(length=10), nullable=False),
    sa.Column('outcome', sa.String(length=10), nullable=False),
    sa.Column('profit_loss', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activities')
    op.drop_table('bot_trades')
    op.drop_table('bot_settings')
    op.drop_table('user')
    with op.batch_alter_table('tick_data', schema=None) as batch_op:
        batch_op.drop_index('idx_market_timestamp')

    op.drop_table('tick_data')
    # ### end Alembic commands ###
